"""empty message

Revision ID: 265f87e8da26
Revises: 31585016a689
Create Date: 2019-12-10 13:28:58.252401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265f87e8da26'
down_revision = '31585016a689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job')
    # ### end Alembic commands ###
