"""rename fields

Revision ID: d63ac4658d57
Revises: 30c62c2b6876
Create Date: 2019-12-09 01:34:23.033760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63ac4658d57'
down_revision = '30c62c2b6876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('_from_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['_to_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'user', ['_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', '_to_id')
    op.drop_column('transaction', '_from_id')
    # ### end Alembic commands ###
